<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ACORN_fc-swatch</name>
   <tag></tag>
   <elementGuidId>4e4e35b5-684a-44dd-9748-25ceb4d45ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div[2]/span/div/div/span/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-swatch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ACORN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;fc-swatch-group&quot;]/div[@class=&quot;fc-outline-target fc-preview-enabled fc-swatch-ca fc-swatch-ca-colorway fc-swatch-ca-79277 fc-swatch-av-145806 fc-swatch-ca-colorway-av-145806 fc-swatch-av-30-f-2-gttt-8-l-1164 fc-swatch-ca-colorway-av-30-f-2-gttt-8-l-1164&quot;]/span[@class=&quot;fc-attribute-value-swatch fc-swatch-selected&quot;]/div[@class=&quot;fc-button-pair&quot;]/div[@class=&quot;fc-button fc-fancy-button&quot;]/span[@class=&quot;fc-button-label&quot;]/span[1]/span[@class=&quot;fc-swatch&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div[2]/span/div/div/span/span/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div/div/span/span/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
