<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_BLACKColorBLACKColorBLACKCloseColorChoos_2ca2a1</name>
   <tag></tag>
   <elementGuidId>38c2c2a4-d704-4c1a-9ad4-b254d2c664f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fluidConfigure']/div/div[2]/div[3]/div/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-nav-flyout fc-nav-flyout-without-ags fc-nav-flyout-open fc-nav-flyout-reveal-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BLACKColorBLACKColorBLACKCloseColorChoose your base colorJet Set Large Saffiano Leather Top-Zip Tote Bag £225.00ColorBLACKBLACKACORNACORNADMIRALADMIRALSOFT PINKSOFT PINKGREENMonogramANUMonogramCloseMonogramAdd up to 3 characters Complimentary0 - 3 CharactersSELECT MONOGRAM COLORGREENSELECT MONOGRAM COLORSELECT MONOGRAM COLORGLITTER GOLDGLITTER GOLDGLITTER SILVERGLITTER SILVERGOLDGOLDSILVERSILVERYELLOWYELLOWORANGEORANGEGREENGREENREDREDPINKPINKMERLOTMERLOTNAVYNAVYROYAL BLUEROYAL BLUEBLACKBLACKSELECT MONOGRAM PLACEMENTFrontSELECT MONOGRAM PLACEMENTFrontSELECT MONOGRAM PLACEMENTFrontBackSELECT MONOGRAM SIZEFont - TNR - 11mmSELECT MONOGRAM SIZEFont - TNR - 11mmSELECT MONOGRAM SIZEFont - TNR - 11mmFont - TNR - 6mm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluidConfigure&quot;)/div[@class=&quot;fc-wrapper fc-bag&quot;]/div[@class=&quot;fc-panel-model&quot;]/div[@class=&quot;fc-panel-menu&quot;]/div[@class=&quot;fc-menu-container fc-menu-item-count-2&quot;]/ul[@class=&quot;fc-nav-flyout fc-nav-flyout-without-ags fc-nav-flyout-open fc-nav-flyout-reveal-left&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fluidConfigure']/div/div[2]/div[3]/div/ul</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post to gallery'])[2]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post to gallery'])[1]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul</value>
   </webElementXpaths>
</WebElementEntity>
