<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_IN _icon</name>
   <tag></tag>
   <elementGuidId>9afd451c-6e8d-4fc2-8605-85db895fc4bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='countrySelector']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HeaderHambergerMenu&quot;)/div[@class=&quot;mk-nav columns&quot;]/div[@class=&quot;utility-nav aria-restricted row custom-font&quot;]/div[@class=&quot;user-items columns&quot;]/div[@class=&quot;user-items-wrapper custom-ul-height&quot;]/ul[@class=&quot;utility-sub-section custom-ul-height icons-allignment&quot;]/li[@class=&quot;search-wrapper loyalty-search-wrapper&quot;]/a[@class=&quot;search-link loyalty-search-link&quot;]/span[1]/span[@class=&quot;icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
</WebElementEntity>
