<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>languageEnglish</name>
   <tag></tag>
   <elementGuidId>8a38ade1-6e0a-46f8-a23b-e9d2fa5d802d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;react-aria-modal-dialog&quot;]/div/div[2]/div[4]/div/ul[2]/div/div[3]/li/div/ul[3]/li[13]/div[2]/ul[2]/li/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#f93</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M0 0h640v160H0z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HeaderHambergerMenu&quot;)/div[@class=&quot;mk-nav columns&quot;]/div[@class=&quot;utility-nav aria-restricted row custom-font&quot;]/div[@class=&quot;region-select-wrap columns large-4&quot;]/ul[@class=&quot;utility-sub-section clearfix flag-allignment&quot;]/li[@class=&quot;country-selector-wrapper&quot;]/div[@class=&quot;country-selector&quot;]/span[@class=&quot;language-selected&quot;]/span[1]/button[@class=&quot;countrySelector&quot;]/span[@class=&quot;countrySelector__svg&quot;]/svg[1]/path[1]</value>
   </webElementProperties>
</WebElementEntity>
