<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>32422d90-41c6-463c-9bc1-3d1eb958d903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='completeShoppingCart']/div/div/div/div[2]/div[3]/klarna-placement/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rcgmal4n.klarnaservices.com/v2/f91b7e00-9315-4b7c-8bdf-cb00c16cb014?ver=1.2.7&amp;a=48bb810e-886f-db8b-6758-2fa423e67335&amp;b=fbjyeKFcf3Oraw57JeNBq&amp;uci=6a68ceaa-3ebc-4199-a3d4-431068e74add&amp;purchase_amount=13000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;completeShoppingCart&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;shopping-bag-cart&quot;]/div[@class=&quot;shopping-bag-cart-body row&quot;]/div[@class=&quot;v-list--md col-xs-12 col-sm-12 col-md-3 shoppingcartrightContents&quot;]/div[@class=&quot;klarna--onsite--messaging&quot;]/klarna-placement[1]/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='completeShoppingCart']/div/div/div/div[2]/div[3]/klarna-placement/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//klarna-placement/iframe</value>
   </webElementXpaths>
</WebElementEntity>
