<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>95c49e60-52c0-4987-b4e0-3ca967fa7bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopping-bag-edit-item-modal']/div/div/div[2]/div[3]/div[4]/div/div/div[3]/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>LT TERRACTTA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://michaelkors.scene7.com/is/image/MichaelKors/30H7GV6T8L-0806_swatch?$swatchLarge$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-bag-edit-item-modal&quot;)/div[@class=&quot;modal-dialog kor-modal__dialog&quot;]/div[@class=&quot;modal-content kor-modal__content&quot;]/div[@class=&quot;modal-body kor-modal__content-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 pull-right col-sm-6&quot;]/div[@class=&quot;v-list&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col--push-05&quot;]/ul[@class=&quot;h-list--inline&quot;]/li[1]/a[@class=&quot;link-padded-box change_color&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-bag-edit-item-modal']/div/div/div[2]/div[3]/div[4]/div/div/div[3]/ul/li/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='LT TERRACTTA']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a/img</value>
   </webElementXpaths>
</WebElementEntity>
