<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_QUICKVIEW_product-image</name>
   <tag></tag>
   <elementGuidId>84b30479-ab61-4c51-b45f-32167cda69da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@class='product-image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//michaelkors.scene7.com/is/image/MichaelKors/30H7GV6T8L-2297_2?$categoryMediumNew$&amp;fmt=pjpeg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Voyager Medium Crossgrain Leather Tote Bag</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-altsrc</name>
      <type>Main</type>
      <value>//michaelkors.scene7.com/is/image/MichaelKors/30H7GV6T8L-2297_2?$categoryMediumNew$&amp;fmt=pjpeg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//michaelkors.scene7.com/is/image/MichaelKors/30H7GV6T8L-2297_IS?$categoryMediumNew$&amp;fmt=pjpeg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageBodyWrapper&quot;)/div[@class=&quot;panel content-wrapper&quot;]/div[@class=&quot;result-panel&quot;]/div[@class=&quot;restricted-content row&quot;]/main[@class=&quot;medium-12 small-12 large-9 columns result-container panel plpIPADmainContainer&quot;]/div[@class=&quot;medium-12 row panel tile-listing&quot;]/ul[@class=&quot;product-wrapper product-wrapper-four-tile&quot;]/li[@class=&quot;product-tile left small-6 medium-3&quot;]/div[@class=&quot;product-tile-container&quot;]/div[@class=&quot;image-panel hover&quot;]/a[1]/div[@class=&quot;product-image-container&quot;]/div[1]/div[@class=&quot;LazyLoad is-visible is-loaded&quot;]/img[@class=&quot;product-image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Voyager Medium Crossgrain Leather Tote Bag']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
   </webElementXpaths>
</WebElementEntity>
