<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_13000_caret</name>
   <tag></tag>
   <elementGuidId>e7d4eac3-5311-4c4d-b16f-e2732a106de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//form[@id='qtyCartChange']/div/button/span[2])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingCartItems&quot;)/div[@class=&quot;shopping-bag-item shipToAddressItem&quot;]/div[@class=&quot;row row--no-gutter-margin available&quot;]/div[@class=&quot;col-md-4 col-sm-5 col--no-gutters hidden-xs&quot;]/div[@class=&quot;row--table&quot;]/div[@class=&quot;col--table col--table-md-4&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;quantity-container&quot;]/div[@class=&quot;form-group select-container&quot;]/div[@class=&quot;input-validation-container&quot;]/form[@id=&quot;qtyCartChange&quot;]/div[@class=&quot;btn-group bootstrap-select new_ay_dropdown form-control form-control--black&quot;]/button[@class=&quot;main_dropdown_new_ay btn dropdown-toggle btn-default&quot;]/span[@class=&quot;caret&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='qtyCartChange']/div/button/span[2])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/form/div/button/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
